#  @Author: Webster Bei Yijie, Joey Junyu Liang
#  @Date: 5/8/2020, 3:16:06 PM
#  @Email: yijie.bei@duke.edu, junyu.liang@duke.edu


version: "3"

networks:
    slaking_network:
        external:
            name: slaking_network
        
services:
    slaking_frontend:
        image: websterbei/slaking-frontendnode:v1
        networks:
             - slaking_network
        ports:
            - "8081:8080"
