#  @Author: Webster Bei Yijie, Joey Junyu Liang
#  @Date: 5/8/2020, 3:15:36 PM
#  @Email: yijie.bei@duke.edu, junyu.liang@duke.edu


version: "3"

networks:
    slaking_network:
        external:
            name: slaking_network
        
services:
    mongodb:
        image: moatez/mongodb:0.0.1 
        container_name: mongodb
        networks:
            - slaking_network
        ports:
            - "27017:27017"

    slaking_backend:
        image: websterbei/slaking-backendnode:v1
        container_name: slaking_backend
        networks:
             - slaking_network
        depends_on:
             - mongodb
        ports:
            - "8082:3000"
