#  @Author: Webster Bei Yijie, Joey Junyu Liang
#  @Date: 5/8/2020, 3:15:53 PM
#  @Email: yijie.bei@duke.edu, junyu.liang@duke.edu


apiVersion: v1
kind: Service
metadata:
  name: model-deployment
spec:
  selector:
    app: model-deployment
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer