apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-gcloud.yml
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: datanode
  name: datanode
spec:
  ports:
  - name: "9866"
    port: 9866
    targetPort: 9866
  - name: "9867"
    port: 9867
    targetPort: 9867
  - name: "9864"
    port: 9864
    targetPort: 9864
  selector:
    io.kompose.service: datanode
status:
  loadBalancer: {}
