version: "3"

services:
  namenode:
    image: websterbei/hadoop-namenode:v1
    container_name: namenode
    ports:
      - 9870:9870
      - 2049:2049/tcp
      - 2049:2049/udp
      - 111:111/tcp
      - 111:111/udp
      - 9000:9000
      - 8020:8020
    # volumes:
      # - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  datanode:
    image: websterbei/hadoop-datanode:v1
    container_name: datanode
    # volumes:
      # - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    ports:
      - 9866:9866
      - 9867:9867
      - 9864:9864
    env_file:
      - ./hadoop.env
  
  # resourcemanager:
  #   image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.1.3-java8
  #   container_name: resourcemanager
  #   environment:
  #     SERVICE_PRECONDITION: "namenode:9870 datanode:9864"
  #   env_file:
  #     - ./hadoop.env

  # nodemanager1:
  #   image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.1.3-java8
  #   container_name: nodemanager
  #   environment:
  #     SERVICE_PRECONDITION: "namenode:9870 datanode:9864 resourcemanager:8088"
  #   env_file:
  #     - ./hadoop.env
  
  # historyserver:
  #   image: bde2020/hadoop-historyserver:2.0.0-hadoop3.1.3-java8
  #   container_name: historyserver
  #   environment:
  #     SERVICE_PRECONDITION: "namenode:9870 datanode:9864 resourcemanager:8088"
  #   volumes:
  #     - hadoop_historyserver:/hadoop/yarn/timeline
  #   env_file:
  #     - ./hadoop.env
  
# volumes:
  # hadoop_namenode:
  # hadoop_datanode:
  # hadoop_historyserver:
