apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-gcloud.yml
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: namenode
  name: namenode
spec:
  ports:
  - name: "9870"
    port: 9870
    targetPort: 9870
  - name: "2049"
    port: 2049
    targetPort: 2049
  - name: 2049-udp
    port: 2049
    protocol: UDP
    targetPort: 2049
  - name: "111"
    port: 111
    targetPort: 111
  - name: 111-udp
    port: 111
    protocol: UDP
    targetPort: 111
  - name: "9000"
    port: 9000
    targetPort: 9000
  - name: "8020"
    port: 8020
    targetPort: 8020
  selector:
    io.kompose.service: namenode
status:
  loadBalancer: {}
